name: deploy
on:
  push:
    paths:
      - 'serverless.yml'
jobs:
  serverless:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: serverless-deploy
      uses: kaskadi/action-slscli@master
      with:
        command: 'deploy -v --force'
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_KEY_SECRET }}
        BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
        SLS_DEPLOY_BUCKET: ${{ secrets.SLS_DEPLOY_BUCKET }}
